### //login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "tester01",
  "password": "GteteqbQQgSr88SwNExUQv2ydb7xuf8c"
}

### 1. Create new client
POST http://localhost:3000/api/client/new
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"c959cbec6f69ecfcc23d07c1f9c898e7"}

{
   "name": "Jenny Svensson",
  "email": "jenny.svensson@example.com",
  "telephone": "0738836820"
}

### 2. Get All Clients
GET http://localhost:3000/api/clients
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"2bd896d8811d8105ec1bd8d998906284"}


### 3. Update Client
PUT http://localhost:3000/api/client/2
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"2bd896d8811d8105ec1bd8d998906284"}

{
  "name": "Alvin Janson",
  "email": "alvin.@example.jansoncom",
  "telephone": "0734905331"
}

### 4. Get All Bills
GET http://localhost:3000/api/bills
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"2bd896d8811d8105ec1bd8d998906284"}

### 5. Get Bill by ID
GET http://localhost:3000/api/bill/1
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"2bd896d8811d8105ec1bd8d998906284"}

### 6. Get Client by ID
GET http://localhost:3000/api/client/2
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"2bd896d8811d8105ec1bd8d998906284"}

### 7. Get All Rooms
GET http://localhost:3000/api/rooms
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"2bd896d8811d8105ec1bd8d998906284"}

### 8. Get Room by ID
GET http://localhost:3000/api/room/1
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"2bd896d8811d8105ec1bd8d998906284"}

